#!/bin/bash

# Quick commands to run on the server to fix polling timeouts
echo "Run these commands on your server to fix the 504 timeout issues:"
echo ""
echo "# 1. First, run diagnostics:"
echo "cd /var/www && ./diagnose-polling-issues.sh"
echo ""
echo "# 2. Update nginx configuration with timeouts:"
echo "sudo cp /var/www/filament-app/../nginx-config.conf /etc/nginx/sites-available/filament-app"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "# 3. Update PHP-FPM settings:"
echo "sudo sed -i 's/max_execution_time = .*/max_execution_time = 300/' /etc/php/8.1/fpm/php.ini"
echo "sudo sed -i 's/memory_limit = .*/memory_limit = 512M/' /etc/php/8.1/fpm/php.ini"
echo "sudo systemctl restart php8.1-fpm"
echo ""
echo "# 4. Restart queue workers:"
echo "sudo systemctl stop filament-queue-worker"
echo "cd /var/www/filament-app"
echo "sudo -u www-data php artisan queue:clear redis"
echo "sudo -u www-data php artisan cache:clear"
echo "sudo systemctl start filament-queue-worker"
echo ""
echo "# 5. Restart polling system:"
echo "sudo -u www-data php artisan polling:reliable stop"
echo "sleep 5"
echo "sudo -u www-data php artisan polling:reliable start"
echo ""
echo "# 6. Check status:"
echo "sudo -u www-data php artisan polling:reliable status"
echo "systemctl status filament-queue-worker"