@echo off
echo ================================
echo    Fresh UserResource Generated!
echo ================================
echo.

cd filament-app

echo Checking if routes exist...
php artisan route:list --name=users

echo.
echo Testing database connection...
php artisan tinker --execute="echo 'Users count: ' . App\Models\User::count();"

echo.
echo ================================
echo    Ready to Test!
echo ================================
echo.
echo 1. Refresh your browser (F5 or Ctrl+F5)
echo 2. Look for "Users" in the sidebar (should appear automatically)
echo 3. Click on "Users" or go to: http://127.0.0.1:8000/admin/users
echo.
echo The UserResource has been freshly generated by Filament!
echo It should now work properly with auto-discovery.
echo.
pause